import { usePageFrameLayoutComponent } from '/~/shared/providers/layout/page-frame.tsx';
import { useSupabaseUser } from '/~/shared/providers/supabase/user.ts';
import { useSupabase } from '/~/shared/providers/supabase/client.ts';
import { Spinner } from '/~/shared/ui/spinner.tsx';
import { useNavigate } from 'react-router-dom';
import { json } from '/~/shared/lib/json.ts';
import useUrlParamName from '/~/shared/lib/react/routing/useUrlParamName.ts';
import { useQuery } from '@tanstack/react-query';
import { SupabaseAutogeneratedDataGrid } from '../../widgets/supabase/autogenerated-data-grid.tsx';
import { generateQueryKeyUniqueSuffix } from '/~/shared/lib/react/WithQueryKeyUniqueSuffix.ts';
import { Suspense } from 'react';

import { publicSchema } from '/~/shared/api/supabase/schemas.ts';

const TablePage = () => {
  const PageFrameComponent = usePageFrameLayoutComponent();
  // const [loading, setLoading] = useState(false);
  // const user = useSupabase();
  const name = useUrlParamName();

  console.log('__TEST__: TablePage: table name:', name);

  if (!name) {
    return <>Error: can't parse url param "name"</>;
  }

  const tableSchema = publicSchema[name];

  if (!tableSchema) {
    return <>Error: no schema with dis table</>;
  }

  return (
    <PageFrameComponent>
      <h3>Table {name}</h3>

      <Suspense fallback={<Spinner />}>
        <SupabaseAutogeneratedDataGrid
          tableName={name}
          queryKeyUniqueSuffix={generateQueryKeyUniqueSuffix()}
        />
      </Suspense>
    </PageFrameComponent>
  );
};

export default TablePage;
