--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1 (Ubuntu 15.1-1.pgdg20.04+1)
-- Dumped by pg_dump version 15.4 (Ubuntu 15.4-1.pgdg20.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: schema_migrations; Type: TABLE DATA; Schema: supabase_migrations; Owner: postgres
--

INSERT INTO "supabase_migrations"."schema_migrations" ("version", "statements", "name") VALUES
	('20231129030618', '{"SET statement_timeout = 0","SET lock_timeout = 0","SET idle_in_transaction_session_timeout = 0","SET client_encoding = ''UTF8''","SET standard_conforming_strings = on","SELECT pg_catalog.set_config(''search_path'', '''', false)","SET check_function_bodies = false","SET xmloption = content","SET client_min_messages = warning","SET row_security = off","CREATE EXTENSION IF NOT EXISTS \"pgsodium\" WITH SCHEMA \"pgsodium\"","CREATE EXTENSION IF NOT EXISTS \"pg_graphql\" WITH SCHEMA \"graphql\"","CREATE EXTENSION IF NOT EXISTS \"pg_stat_statements\" WITH SCHEMA \"extensions\"","CREATE EXTENSION IF NOT EXISTS \"pgcrypto\" WITH SCHEMA \"extensions\"","CREATE EXTENSION IF NOT EXISTS \"pgjwt\" WITH SCHEMA \"extensions\"","CREATE EXTENSION IF NOT EXISTS \"supabase_vault\" WITH SCHEMA \"vault\"","CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\" WITH SCHEMA \"extensions\"","SET default_tablespace = ''''","SET default_table_access_method = \"heap\"","CREATE TABLE IF NOT EXISTS \"public\".\"authors\" (
    \"id\" bigint NOT NULL,
    \"lastname_name_patronymic\" \"text\" NOT NULL,
    \"created_at\" timestamp with time zone DEFAULT \"now\"() NOT NULL,
    \"birth_year\" bigint,
    \"death_year\" bigint,
    \"approximate_years\" boolean DEFAULT false NOT NULL,
    \"updated_at\" timestamp with time zone DEFAULT \"now\"() NOT NULL
)","ALTER TABLE \"public\".\"authors\" OWNER TO \"postgres\"","ALTER TABLE \"public\".\"authors\" ALTER COLUMN \"id\" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME \"public\".\"author_id_seq\"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)","CREATE TABLE IF NOT EXISTS \"public\".\"citations\" (
    \"id\" bigint NOT NULL,
    \"english_text\" \"text\",
    \"author_id\" bigint NOT NULL,
    \"year\" bigint,
    \"created_at\" timestamp with time zone DEFAULT \"now\"() NOT NULL,
    \"updated_at\" timestamp without time zone DEFAULT \"now\"() NOT NULL,
    \"original_language_text\" \"text\"
)","ALTER TABLE \"public\".\"citations\" OWNER TO \"postgres\"","ALTER TABLE \"public\".\"citations\" ALTER COLUMN \"id\" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME \"public\".\"citations_id_seq\"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)","CREATE TABLE IF NOT EXISTS \"public\".\"country\" (
    \"id\" bigint NOT NULL,
    \"name\" \"text\",
    \"created_at\" timestamp with time zone DEFAULT \"now\"() NOT NULL,
    \"updated_at\" timestamp with time zone DEFAULT \"now\"(),
    \"found_year\" bigint,
    \"next_rename_year\" bigint
)","ALTER TABLE \"public\".\"country\" OWNER TO \"postgres\"","ALTER TABLE \"public\".\"country\" ALTER COLUMN \"id\" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME \"public\".\"country_id_seq\"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)","CREATE TABLE IF NOT EXISTS \"public\".\"place\" (
    \"id\" bigint NOT NULL,
    \"name\" \"text\" DEFAULT ''in''::\"text\" NOT NULL,
    \"created_at\" timestamp with time zone DEFAULT \"now\"() NOT NULL,
    \"updated_at\" timestamp with time zone DEFAULT \"now\"() NOT NULL
)","ALTER TABLE \"public\".\"place\" OWNER TO \"postgres\"","ALTER TABLE \"public\".\"place\" ALTER COLUMN \"id\" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME \"public\".\"place_id_seq\"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)","CREATE TABLE IF NOT EXISTS \"public\".\"province\" (
    \"id\" bigint NOT NULL,
    \"name\" \"text\" NOT NULL,
    \"country_id\" bigint NOT NULL,
    \"created_at\" timestamp with time zone DEFAULT \"now\"() NOT NULL,
    \"updated_at\" timestamp with time zone DEFAULT \"now\"() NOT NULL
)","ALTER TABLE \"public\".\"province\" OWNER TO \"postgres\"","ALTER TABLE \"public\".\"province\" ALTER COLUMN \"id\" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME \"public\".\"province_id_seq\"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)","CREATE TABLE IF NOT EXISTS \"public\".\"town\" (
    \"id\" bigint NOT NULL,
    \"name\" \"text\" NOT NULL,
    \"province_id\" bigint NOT NULL,
    \"created_at\" timestamp with time zone DEFAULT \"now\"() NOT NULL,
    \"updated_at\" timestamp with time zone DEFAULT \"now\"() NOT NULL
)","ALTER TABLE \"public\".\"town\" OWNER TO \"postgres\"","ALTER TABLE \"public\".\"town\" ALTER COLUMN \"id\" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME \"public\".\"town_id_seq\"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)","ALTER TABLE ONLY \"public\".\"authors\"
    ADD CONSTRAINT \"author_pkey\" PRIMARY KEY (\"id\")","ALTER TABLE ONLY \"public\".\"citations\"
    ADD CONSTRAINT \"citations_pkey\" PRIMARY KEY (\"id\")","ALTER TABLE ONLY \"public\".\"country\"
    ADD CONSTRAINT \"country_pkey\" PRIMARY KEY (\"id\")","ALTER TABLE ONLY \"public\".\"place\"
    ADD CONSTRAINT \"place_pkey\" PRIMARY KEY (\"id\")","ALTER TABLE ONLY \"public\".\"province\"
    ADD CONSTRAINT \"province_pkey\" PRIMARY KEY (\"id\")","ALTER TABLE ONLY \"public\".\"town\"
    ADD CONSTRAINT \"town_pkey\" PRIMARY KEY (\"id\")","ALTER TABLE ONLY \"public\".\"citations\"
    ADD CONSTRAINT \"citations_author_id_fkey\" FOREIGN KEY (\"author_id\") REFERENCES \"public\".\"authors\"(\"id\") ON UPDATE CASCADE ON DELETE RESTRICT","ALTER TABLE ONLY \"public\".\"province\"
    ADD CONSTRAINT \"province_country_id_fkey\" FOREIGN KEY (\"country_id\") REFERENCES \"public\".\"country\"(\"id\") ON UPDATE CASCADE ON DELETE RESTRICT","ALTER TABLE ONLY \"public\".\"town\"
    ADD CONSTRAINT \"town_province_id_fkey\" FOREIGN KEY (\"province_id\") REFERENCES \"public\".\"province\"(\"id\") ON UPDATE CASCADE ON DELETE RESTRICT","REVOKE USAGE ON SCHEMA \"public\" FROM PUBLIC","GRANT USAGE ON SCHEMA \"public\" TO \"postgres\"","GRANT USAGE ON SCHEMA \"public\" TO \"anon\"","GRANT USAGE ON SCHEMA \"public\" TO \"authenticated\"","GRANT USAGE ON SCHEMA \"public\" TO \"service_role\"","GRANT ALL ON TABLE \"public\".\"authors\" TO \"anon\"","GRANT ALL ON TABLE \"public\".\"authors\" TO \"authenticated\"","GRANT ALL ON TABLE \"public\".\"authors\" TO \"service_role\"","GRANT ALL ON SEQUENCE \"public\".\"author_id_seq\" TO \"anon\"","GRANT ALL ON SEQUENCE \"public\".\"author_id_seq\" TO \"authenticated\"","GRANT ALL ON SEQUENCE \"public\".\"author_id_seq\" TO \"service_role\"","GRANT ALL ON TABLE \"public\".\"citations\" TO \"anon\"","GRANT ALL ON TABLE \"public\".\"citations\" TO \"authenticated\"","GRANT ALL ON TABLE \"public\".\"citations\" TO \"service_role\"","GRANT ALL ON SEQUENCE \"public\".\"citations_id_seq\" TO \"anon\"","GRANT ALL ON SEQUENCE \"public\".\"citations_id_seq\" TO \"authenticated\"","GRANT ALL ON SEQUENCE \"public\".\"citations_id_seq\" TO \"service_role\"","GRANT ALL ON TABLE \"public\".\"country\" TO \"anon\"","GRANT ALL ON TABLE \"public\".\"country\" TO \"authenticated\"","GRANT ALL ON TABLE \"public\".\"country\" TO \"service_role\"","GRANT ALL ON SEQUENCE \"public\".\"country_id_seq\" TO \"anon\"","GRANT ALL ON SEQUENCE \"public\".\"country_id_seq\" TO \"authenticated\"","GRANT ALL ON SEQUENCE \"public\".\"country_id_seq\" TO \"service_role\"","GRANT ALL ON TABLE \"public\".\"place\" TO \"anon\"","GRANT ALL ON TABLE \"public\".\"place\" TO \"authenticated\"","GRANT ALL ON TABLE \"public\".\"place\" TO \"service_role\"","GRANT ALL ON SEQUENCE \"public\".\"place_id_seq\" TO \"anon\"","GRANT ALL ON SEQUENCE \"public\".\"place_id_seq\" TO \"authenticated\"","GRANT ALL ON SEQUENCE \"public\".\"place_id_seq\" TO \"service_role\"","GRANT ALL ON TABLE \"public\".\"province\" TO \"anon\"","GRANT ALL ON TABLE \"public\".\"province\" TO \"authenticated\"","GRANT ALL ON TABLE \"public\".\"province\" TO \"service_role\"","GRANT ALL ON SEQUENCE \"public\".\"province_id_seq\" TO \"anon\"","GRANT ALL ON SEQUENCE \"public\".\"province_id_seq\" TO \"authenticated\"","GRANT ALL ON SEQUENCE \"public\".\"province_id_seq\" TO \"service_role\"","GRANT ALL ON TABLE \"public\".\"town\" TO \"anon\"","GRANT ALL ON TABLE \"public\".\"town\" TO \"authenticated\"","GRANT ALL ON TABLE \"public\".\"town\" TO \"service_role\"","GRANT ALL ON SEQUENCE \"public\".\"town_id_seq\" TO \"anon\"","GRANT ALL ON SEQUENCE \"public\".\"town_id_seq\" TO \"authenticated\"","GRANT ALL ON SEQUENCE \"public\".\"town_id_seq\" TO \"service_role\"","ALTER DEFAULT PRIVILEGES FOR ROLE \"postgres\" IN SCHEMA \"public\" GRANT ALL ON SEQUENCES  TO \"postgres\"","ALTER DEFAULT PRIVILEGES FOR ROLE \"postgres\" IN SCHEMA \"public\" GRANT ALL ON SEQUENCES  TO \"anon\"","ALTER DEFAULT PRIVILEGES FOR ROLE \"postgres\" IN SCHEMA \"public\" GRANT ALL ON SEQUENCES  TO \"authenticated\"","ALTER DEFAULT PRIVILEGES FOR ROLE \"postgres\" IN SCHEMA \"public\" GRANT ALL ON SEQUENCES  TO \"service_role\"","ALTER DEFAULT PRIVILEGES FOR ROLE \"postgres\" IN SCHEMA \"public\" GRANT ALL ON FUNCTIONS  TO \"postgres\"","ALTER DEFAULT PRIVILEGES FOR ROLE \"postgres\" IN SCHEMA \"public\" GRANT ALL ON FUNCTIONS  TO \"anon\"","ALTER DEFAULT PRIVILEGES FOR ROLE \"postgres\" IN SCHEMA \"public\" GRANT ALL ON FUNCTIONS  TO \"authenticated\"","ALTER DEFAULT PRIVILEGES FOR ROLE \"postgres\" IN SCHEMA \"public\" GRANT ALL ON FUNCTIONS  TO \"service_role\"","ALTER DEFAULT PRIVILEGES FOR ROLE \"postgres\" IN SCHEMA \"public\" GRANT ALL ON TABLES  TO \"postgres\"","ALTER DEFAULT PRIVILEGES FOR ROLE \"postgres\" IN SCHEMA \"public\" GRANT ALL ON TABLES  TO \"anon\"","ALTER DEFAULT PRIVILEGES FOR ROLE \"postgres\" IN SCHEMA \"public\" GRANT ALL ON TABLES  TO \"authenticated\"","ALTER DEFAULT PRIVILEGES FOR ROLE \"postgres\" IN SCHEMA \"public\" GRANT ALL ON TABLES  TO \"service_role\"","RESET ALL"}', 'remote_schema'),
	('20231129093821', '{"alter table \"public\".\"province\" drop constraint \"province_country_id_fkey\"","alter table \"public\".\"town\" drop constraint \"town_province_id_fkey\"","alter table \"public\".\"citations\" drop constraint \"citations_author_id_fkey\"","alter table \"public\".\"province\" drop constraint \"province_pkey\"","drop index if exists \"public\".\"province_pkey\"","drop table \"public\".\"province\"","create table \"public\".\"event\" (
    \"id\" bigint generated by default as identity not null,
    \"name\" text not null,
    \"created_at\" timestamp with time zone not null default now(),
    \"updated_at\" timestamp with time zone not null default now(),
    \"start_year\" bigint not null,
    \"start_month\" smallint not null,
    \"end_year\" bigint,
    \"end_month\" smallint,
    \"place_id\" bigint
)","alter table \"public\".\"authors\" add column \"birth_town\" bigint","alter table \"public\".\"citations\" add column \"event_id\" bigint","alter table \"public\".\"citations\" add column \"place_id\" bigint","alter table \"public\".\"place\" add column \"town_id\" bigint not null","alter table \"public\".\"town\" drop column \"province_id\"","alter table \"public\".\"town\" add column \"country_id\" bigint not null","CREATE UNIQUE INDEX event_pkey ON public.event USING btree (id)","alter table \"public\".\"event\" add constraint \"event_pkey\" PRIMARY KEY using index \"event_pkey\"","alter table \"public\".\"authors\" add constraint \"authors_birth_town_fkey\" FOREIGN KEY (birth_town) REFERENCES town(id) ON UPDATE CASCADE not valid","alter table \"public\".\"authors\" validate constraint \"authors_birth_town_fkey\"","alter table \"public\".\"citations\" add constraint \"citations_event_id_fkey\" FOREIGN KEY (event_id) REFERENCES event(id) ON UPDATE CASCADE not valid","alter table \"public\".\"citations\" validate constraint \"citations_event_id_fkey\"","alter table \"public\".\"citations\" add constraint \"citations_place_id_fkey\" FOREIGN KEY (place_id) REFERENCES place(id) not valid","alter table \"public\".\"citations\" validate constraint \"citations_place_id_fkey\"","alter table \"public\".\"event\" add constraint \"event_place_id_fkey\" FOREIGN KEY (place_id) REFERENCES place(id) ON UPDATE CASCADE not valid","alter table \"public\".\"event\" validate constraint \"event_place_id_fkey\"","alter table \"public\".\"place\" add constraint \"place_town_id_fkey\" FOREIGN KEY (town_id) REFERENCES town(id) ON UPDATE CASCADE not valid","alter table \"public\".\"place\" validate constraint \"place_town_id_fkey\"","alter table \"public\".\"town\" add constraint \"town_country_id_fkey\" FOREIGN KEY (country_id) REFERENCES country(id) ON UPDATE CASCADE not valid","alter table \"public\".\"town\" validate constraint \"town_country_id_fkey\"","alter table \"public\".\"citations\" add constraint \"citations_author_id_fkey\" FOREIGN KEY (author_id) REFERENCES authors(id) ON UPDATE CASCADE not valid","alter table \"public\".\"citations\" validate constraint \"citations_author_id_fkey\""}', 'remote_schema'),
	('20231129114012', '{"create table \"public\".\"profiles\" (
    \"id\" uuid not null,
    \"updated_at\" timestamp with time zone,
    \"username\" text,
    \"full_name\" text,
    \"avatar_url\" text,
    \"website\" text
)","alter table \"public\".\"profiles\" enable row level security","CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id)","CREATE UNIQUE INDEX profiles_username_key ON public.profiles USING btree (username)","alter table \"public\".\"profiles\" add constraint \"profiles_pkey\" PRIMARY KEY using index \"profiles_pkey\"","alter table \"public\".\"profiles\" add constraint \"profiles_id_fkey\" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid","alter table \"public\".\"profiles\" validate constraint \"profiles_id_fkey\"","alter table \"public\".\"profiles\" add constraint \"profiles_username_key\" UNIQUE using index \"profiles_username_key\"","alter table \"public\".\"profiles\" add constraint \"username_length\" CHECK ((char_length(username) >= 3)) not valid","alter table \"public\".\"profiles\" validate constraint \"username_length\"","set check_function_bodies = off","CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>''full_name'', new.raw_user_meta_data->>''avatar_url'');
  return new;
end;
$function$","create policy \"Public profiles are viewable by everyone.\"
on \"public\".\"profiles\"
as permissive
for select
to public
using (true)","create policy \"Users can insert their own profile.\"
on \"public\".\"profiles\"
as permissive
for insert
to public
with check ((auth.uid() = id))","create policy \"Users can update own profile.\"
on \"public\".\"profiles\"
as permissive
for update
to public
using ((auth.uid() = id))"}', 'user_management_starter');


--
-- PostgreSQL database dump complete
--

RESET ALL;
