import { FnKeySetter } from '/~/shared/api/supabase/types/keys.types.ts';
import { NEW_RECORD_ID } from '/~/widgets/supabase/autogenerated-data-grid/const.ts';

export type UseCreateDummyRecordArgs = {
  rowKeySetter: FnKeySetter;
};

export const useCreateDummyRecord = (
  { rowKeySetter }: UseCreateDummyRecordArgs,
) => {
  return {
    createDummyRecord: (fieldsNamesEditable: string[]) => {
      const result = {
        /** Fill with empty strings to prevent warn "A component is changing an uncontrolled input to be controlled" */
        ...Object.fromEntries(fieldsNamesEditable.map((n) => [n, ''])),
      };

      rowKeySetter(result, NEW_RECORD_ID);
      return result;
    },
  };
};
