import { FnKeySetter } from '/~/shared/api/supabase/types/keys.types.ts';
import { NEW_RECORD_ID } from '/~/widgets/supabase/autogenerated-data-grid/const.ts';
import {
  DbFieldInfo,
  DbTable,
} from '/~/shared/api/supabase/json-schema.types.ts';

export type UseCreateDummyRecordArgs = {
  rowKeySetter: FnKeySetter;
  tableSchema: DbTable;
};

export const useCreateDummyRecord = (
  { rowKeySetter, tableSchema }: UseCreateDummyRecordArgs,
) => {
  return {
    createDummyRecord: (fieldsNamesEditable: string[]) => {
      const result = {
        /** Fill with empty strings to prevent warn "A component is changing an uncontrolled input to be controlled" */
        ...Object.fromEntries(fieldsNamesEditable.map((n) => {
          const fieldInfo: DbFieldInfo = tableSchema[n];

          const defaultValue = fieldInfo?.type === 'boolean' ? undefined : '';

          return [n, defaultValue];
        })),
      };

      rowKeySetter(result, NEW_RECORD_ID);
      return result;
    },
  };
};
