export const COOKIE_NAME_SUPABASE_ACCESS_TOKEN = 'my-supabase-access-token';
export const COOKIE_NAME_SUPABASE_REFRESH_TOKEN = 'my-supabase-refresh-token';

export const COLUMN_NAME_EDITABLE = '_editable';
export const COLUMN_NAME_DELETABLE = '_deletable';

export const COLUMNS_IDS = ['id'];
export const COLUMNS_AUTOGENERATED = [
  'id',
  'created_by',
  'updated_by',
  'created_at',
  'updated_at',
  COLUMN_NAME_EDITABLE,
  COLUMN_NAME_DELETABLE,
];
export const COLUMNS_SHOW_FIRST = ['id', COLUMN_NAME_EDITABLE, 'name'];
export const COLUMNS_SHOW_LAST = [
  'created_by',
  'updated_by',
  'created_at',
  'updated_at',
  COLUMN_NAME_DELETABLE,
];

export const TABLES_HIDDEN = ['content_item'];
