export const COOKIE_NAME_SUPABASE_ACCESS_TOKEN = 'my-supabase-access-token';
export const COOKIE_NAME_SUPABASE_REFRESH_TOKEN = 'my-supabase-refresh-token';

export const FIELDS_IDS = ['id'];
export const FIELDS_AUTOGENERATED = ['id', 'created_at', 'updated_at'];
export const FIELDS_SHOW_FIRST = ['id', 'name'];
export const FIELDS_SHOW_LAST = [
  'created_by',
  'updated_by',
  'created_at',
  'updated_at',
];
