alter table "public"."town" drop constraint "town_country_id_fkey";

alter table "public"."country" drop constraint "country_pkey";

drop index if exists "public"."country_pkey";

drop table "public"."country";

create table "public"."countries" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "found_year" bigint,
    "next_rename_year" bigint
);


CREATE UNIQUE INDEX country_pkey ON public.countries USING btree (id);

alter table "public"."countries" add constraint "country_pkey" PRIMARY KEY using index "country_pkey";

alter table "public"."town" add constraint "town_country_id_fkey" FOREIGN KEY (country_id) REFERENCES countries(id) ON UPDATE CASCADE not valid;

alter table "public"."town" validate constraint "town_country_id_fkey";


