alter table "public"."province" drop constraint "province_country_id_fkey";

alter table "public"."town" drop constraint "town_province_id_fkey";

alter table "public"."citations" drop constraint "citations_author_id_fkey";

alter table "public"."province" drop constraint "province_pkey";

drop index if exists "public"."province_pkey";

drop table "public"."province";

create table "public"."event" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "start_year" bigint not null,
    "start_month" smallint not null,
    "end_year" bigint,
    "end_month" smallint,
    "place_id" bigint
);


alter table "public"."authors" add column "birth_town" bigint;

alter table "public"."citations" add column "event_id" bigint;

alter table "public"."citations" add column "place_id" bigint;

alter table "public"."place" add column "town_id" bigint not null;

alter table "public"."town" drop column "province_id";

alter table "public"."town" add column "country_id" bigint not null;

CREATE UNIQUE INDEX event_pkey ON public.event USING btree (id);

alter table "public"."event" add constraint "event_pkey" PRIMARY KEY using index "event_pkey";

alter table "public"."authors" add constraint "authors_birth_town_fkey" FOREIGN KEY (birth_town) REFERENCES town(id) ON UPDATE CASCADE not valid;

alter table "public"."authors" validate constraint "authors_birth_town_fkey";

alter table "public"."citations" add constraint "citations_event_id_fkey" FOREIGN KEY (event_id) REFERENCES event(id) ON UPDATE CASCADE not valid;

alter table "public"."citations" validate constraint "citations_event_id_fkey";

alter table "public"."citations" add constraint "citations_place_id_fkey" FOREIGN KEY (place_id) REFERENCES place(id) not valid;

alter table "public"."citations" validate constraint "citations_place_id_fkey";

alter table "public"."event" add constraint "event_place_id_fkey" FOREIGN KEY (place_id) REFERENCES place(id) ON UPDATE CASCADE not valid;

alter table "public"."event" validate constraint "event_place_id_fkey";

alter table "public"."place" add constraint "place_town_id_fkey" FOREIGN KEY (town_id) REFERENCES town(id) ON UPDATE CASCADE not valid;

alter table "public"."place" validate constraint "place_town_id_fkey";

alter table "public"."town" add constraint "town_country_id_fkey" FOREIGN KEY (country_id) REFERENCES country(id) ON UPDATE CASCADE not valid;

alter table "public"."town" validate constraint "town_country_id_fkey";

alter table "public"."citations" add constraint "citations_author_id_fkey" FOREIGN KEY (author_id) REFERENCES authors(id) ON UPDATE CASCADE not valid;

alter table "public"."citations" validate constraint "citations_author_id_fkey";


