drop policy "RLS: countries: delete" on "public"."countries";

alter table "public"."event" drop constraint "event_place_id_fkey";

alter table "public"."place" drop constraint "place_town_id_fkey";

alter table "public"."town" drop constraint "town_country_id_fkey";

alter table "public"."authors" drop constraint "authors_birth_town_fkey";

alter table "public"."citations" drop constraint "citations_event_id_fkey";

alter table "public"."citations" drop constraint "citations_place_id_fkey";

alter table "public"."event" drop constraint "event_pkey";

alter table "public"."place" drop constraint "place_pkey";

alter table "public"."town" drop constraint "town_pkey";

drop index if exists "public"."event_pkey";

drop index if exists "public"."place_pkey";

drop index if exists "public"."town_pkey";

drop table "public"."event";

drop table "public"."place";

drop table "public"."town";

create table "public"."events" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "start_year" bigint not null,
    "start_month" smallint not null,
    "end_year" bigint,
    "end_month" smallint,
    "place_id" bigint,
    "created_by" bigint,
    "updated_by" bigint
);


create table "public"."places" (
    "id" bigint generated by default as identity not null,
    "name" text not null default 'in'::text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "town_id" bigint not null,
    "created_by" bigint,
    "updated_by" bigint
);


create table "public"."towns" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "country_id" bigint not null,
    "created_by" bigint,
    "updated_by" bigint
);


alter table "public"."authors" add column "created_by" bigint;

alter table "public"."authors" add column "updated_by" bigint;

alter table "public"."citations" add column "created_by" bigint;

alter table "public"."citations" add column "updated_by" bigint;

alter table "public"."profiles" add column "created_at" timestamp with time zone default now();

CREATE UNIQUE INDEX event_pkey ON public.events USING btree (id);

CREATE UNIQUE INDEX place_pkey ON public.places USING btree (id);

CREATE UNIQUE INDEX town_pkey ON public.towns USING btree (id);

alter table "public"."events" add constraint "event_pkey" PRIMARY KEY using index "event_pkey";

alter table "public"."places" add constraint "place_pkey" PRIMARY KEY using index "place_pkey";

alter table "public"."towns" add constraint "town_pkey" PRIMARY KEY using index "town_pkey";

alter table "public"."authors" add constraint "authors_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."authors" validate constraint "authors_created_by_fkey";

alter table "public"."authors" add constraint "authors_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."authors" validate constraint "authors_updated_by_fkey";

alter table "public"."citations" add constraint "citations_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."citations" validate constraint "citations_created_by_fkey";

alter table "public"."citations" add constraint "citations_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."citations" validate constraint "citations_updated_by_fkey";

alter table "public"."events" add constraint "events_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."events" validate constraint "events_created_by_fkey";

alter table "public"."events" add constraint "events_place_id_fkey" FOREIGN KEY (place_id) REFERENCES places(id) ON UPDATE CASCADE not valid;

alter table "public"."events" validate constraint "events_place_id_fkey";

alter table "public"."events" add constraint "events_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."events" validate constraint "events_updated_by_fkey";

alter table "public"."places" add constraint "places_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."places" validate constraint "places_created_by_fkey";

alter table "public"."places" add constraint "places_town_id_fkey" FOREIGN KEY (town_id) REFERENCES towns(id) ON UPDATE CASCADE not valid;

alter table "public"."places" validate constraint "places_town_id_fkey";

alter table "public"."places" add constraint "places_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."places" validate constraint "places_updated_by_fkey";

alter table "public"."towns" add constraint "towns_country_id_fkey" FOREIGN KEY (country_id) REFERENCES countries(id) ON UPDATE CASCADE not valid;

alter table "public"."towns" validate constraint "towns_country_id_fkey";

alter table "public"."towns" add constraint "towns_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."towns" validate constraint "towns_created_by_fkey";

alter table "public"."towns" add constraint "towns_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."towns" validate constraint "towns_updated_by_fkey";

alter table "public"."authors" add constraint "authors_birth_town_fkey" FOREIGN KEY (birth_town) REFERENCES towns(id) ON UPDATE CASCADE not valid;

alter table "public"."authors" validate constraint "authors_birth_town_fkey";

alter table "public"."citations" add constraint "citations_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON UPDATE CASCADE not valid;

alter table "public"."citations" validate constraint "citations_event_id_fkey";

alter table "public"."citations" add constraint "citations_place_id_fkey" FOREIGN KEY (place_id) REFERENCES places(id) not valid;

alter table "public"."citations" validate constraint "citations_place_id_fkey";

set check_function_bodies = off;

create policy "RLS: countries: delete"
on "public"."countries"
as permissive
for delete
to authenticated
using (rls_countries_delete(countries.*));


CREATE TRIGGER on_authors_edit_fill_update BEFORE UPDATE ON public.authors FOR EACH ROW EXECUTE FUNCTION handle_fill_updated();

CREATE TRIGGER on_authors_new_fill_created_by BEFORE INSERT ON public.authors FOR EACH ROW EXECUTE FUNCTION handle_fill_created_by();

CREATE TRIGGER on_citations_edit_fill_update BEFORE UPDATE ON public.citations FOR EACH ROW EXECUTE FUNCTION handle_fill_updated();

CREATE TRIGGER on_citations_new_fill_created_by BEFORE INSERT ON public.citations FOR EACH ROW EXECUTE FUNCTION handle_fill_created_by();

CREATE TRIGGER on_events_edit_fill_update BEFORE UPDATE ON public.events FOR EACH ROW EXECUTE FUNCTION handle_fill_updated();

CREATE TRIGGER on_events_new_fill_created_by BEFORE INSERT ON public.events FOR EACH ROW EXECUTE FUNCTION handle_fill_created_by();

CREATE TRIGGER on_places_edit_fill_update BEFORE UPDATE ON public.places FOR EACH ROW EXECUTE FUNCTION handle_fill_updated();

CREATE TRIGGER on_places_new_fill_created_by BEFORE INSERT ON public.places FOR EACH ROW EXECUTE FUNCTION handle_fill_created_by();

CREATE TRIGGER on_towns_edit_fill_update BEFORE UPDATE ON public.towns FOR EACH ROW EXECUTE FUNCTION handle_fill_updated();

CREATE TRIGGER on_towns_new_fill_created_by BEFORE INSERT ON public.towns FOR EACH ROW EXECUTE FUNCTION handle_fill_created_by();


