import { JsonView } from '/~/shared/ui/json-view.tsx';
import { WithQueryKeyUniqueSuffix } from '/~/shared/lib/react/query/key.ts';
import { useQuery } from '@tanstack/react-query';
import { useSupabase } from '/~/shared/providers/supabase/client.ts';

export type SupabaseAutogeneratedDataGridProps = {
  tableName: string;
} & WithQueryKeyUniqueSuffix;

export const SupabaseAutogeneratedDataGrid = (
  { tableName, queryKeyUniqueSuffix }: SupabaseAutogeneratedDataGridProps,
) => {
  console.debug(
    'SupabaseAutogeneratedDataGrid: queryKeyUniqueSuffix:',
    queryKeyUniqueSuffix,
  );

  const supabase = useSupabase();

  const { data, error } = useQuery({
    queryKey: ['SupabaseAutogeneratedDataGrid' + queryKeyUniqueSuffix],
    queryFn: () => supabase?.from(tableName).select('*'),
  });

  return <JsonView data={data} />;
};
